-- SQL Inserts generated from txt file (100% OK Slovak + Emoji)
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 17', 'Apple', 'iPhone 17', 'Mobile', '📱 6.1" Super Retina XDR OLED s technológiou LTPO (ProMotion 120Hz).', '["⚠️ Display Scratch Test: i17 má novú vrstvu proti odleskom. Skontroluj pod ostrým svetlom, či na nej nie sú \"olejové škvrny\" – u prvých kusov sa táto vrstva niekedy nerovnomerne nanášala.","⚠️ Vibrácie: Taptic Engine pri i17 pôsobí jemnejšie."]', '🔋 • Čip: A19 (3nm/2nm hybrid) – základný čip, ktorý má však rovnaký Neural Engine ako Pro verzia pre plnú podporu Apple Intelligence.
    • RAM: 8GB (dostatočné pre AI, ale menej ako 12GB u Pro).
    • Audit pravidlo: iPhone 17 ukazuje cykly batérie v menu.
    • Kontrola: Pri takmer novom kuse vyžaduj 100 % zdravie. Ak má mobil po 3 mesiacoch 98 %, majiteľ ho pravdepodobne nabíjal lacnými neoriginálnymi nabíjačkami.', 'Letecký hliník a nové matné sklo, ktoré je menej náchylné na odtlačky.', '• Veta na zľavu: „Je to skvelý mobil, ale v marci sa očakáva nový SE, ktorý mu bude konkurovať. Spustíte na 700 , keďže má už 150 cyklov batérie?“
    • Veta na preverenie: „Môžem skúsiť ten nový 120Hz displej pri rýchlom skrolovaní na webe?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 17 Air', 'Apple', 'iPhone 17 Air', 'Mobile', '📱 6.6" OLED s technológiou TDDI (integrovaný dotyk do vrstvy displeja), čo umožnilo extrémne zníženie hrúbky.', '["⚠️ Tuhosť: Skús telefón jemne (naozaj jemne!) v ruke \"napružiť\". Nesmieš počuť žiadne pukanie alebo vŕzganie lepidla.","⚠️ Audio: Reproduktory sú v tomto modeli menšie. Pusti zvuk na max – ak drnčia, sú na hranici svojich fyzických možností."]', '🔋 • Čip: A19 (3nm/2nm hybrid) – optimalizovaný na nízku produkciu tepla.
    • Audit pravidlo: iPhone 17 Air ukazuje cykly batérie v menu.
    • Kritický bod: Kvôli hrúbke má menšiu batériu než iPhone 17 Plus. Výdrž je "celodenná", ale nie "dvojdňová".
    • Kontrola: Pri zánovnom kuse vyžaduj 100 % zdravie. Ak uvidíš 97 % po mesiaci, batéria trpí kvôli rýchlemu vybíjaniu pri vysokej záťaži (hranatý dizajn horšie odvádza teplo).', 'peciálna zliatina hliníka a titánu pre zvýšenú tuhosť (prevencia proti ohybu).', '• Veta na zľavu: „Model Air je krásny, ale batéria je citeľne slabšia než u i17 Pro. Navyše pri tejto hrúbke sa bojím o životnosť konštrukcie. Spustíte na 920 ?“
    • Veta na preverenie: „Môžem si overiť, či je telefón úplne rovný na tejto sklenenej tabuli?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 17 Pro', 'Apple', 'iPhone 17 Pro', 'Mobile', '📱 6.3" LTPO Super Retina XDR OLED (ProMotion 1-120Hz).', '["⚠️ Haptika: Skús stlačiť Camera Control. Odozva musí byť \"pevná\". Ak cítiš vibráciu v celom tele mobilu (nielen pod prstom), Taptic Engine je zle uchytený.","⚠️ Audio: i17 Pro má vylepšený horný reproduktor pre širšie stereo. Pusti si Spatial Audio test na YouTube."]', '🔋 • Čip: A19 Pro (2nm) – energetický zázrak, ktorý takmer neprodukuje odpadové teplo.
    • RAM: 12GB – zásadné pre lokálny chod Apple Intelligence (modely i16 Pro mali len 8GB).
    • Audit pravidlo: iPhone 17 Pro ukazuje cykly batérie a dátum prvého použitia.
    • Kontrola: Pri modeli z konca roka 2025 musí byť zdravie batérie 100 %. Ak uvidíš 98 % a menej, pýtaj sa na používanie v extrémnych podmienkach.', 'Titán Grade 5 s novou povrchovou úpravou odolnou voči odtlačkom prstov.', '• Veta na zľavu: „Tento iPhone 17 Pro je super, ale vidím, že už má 120 cyklov za necelé 3 mesiace. To je intenzívne používanie. Spustíte na 1080 ?“
    • Veta na preverenie: „Rád by som skúsil ten nový 48MP zoom vonku na dennom svetle, či je obraz čistý.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 17 Pro Max', 'Apple', 'iPhone 17 Pro Max', 'Mobile', '📱 6.9" LTPO Super Retina XDR OLED s novou vrstvou Ceramic Shield 2 (odolnejšia voči mikro-škrabancom).', '["⚠️ Display Glitch: Skontroluj, či pri prepínaní medzi aplikáciami nevzniká \"stutter\" (zaseknutie). Niektoré prvé série i17 mali chybu firmvéru displeja.","⚠️ LiDAR 2.0: Skús appku Meradlo v tme. Nový LiDAR by mal vidieť detaily aj na 5 metrov."]', '🔋 • Čip: A19 Pro (2nm proces) – prvý čip tejto kategórie, extrémne výkonný pre lokálnu AI.
    • RAM: 12GB (štandard u i17 Pro) – kľúčové pre plynulý multitasking.
    • Audit pravidlo: iPhone 17 Pro Max ukazuje cykly batérie a presný dátum aktivácie.
    • Kontrola: Keďže je mobil vonku len pár mesiacov, zdravie batérie musí byť 100 %. Ak uvidíš 99 %, pýtaj sa na dôvod (pravdepodobne časté používanie MagSafe v aute).', 'Nový titánový zliatinový rám s vysokou hustotou (odolnejší voči nárazom).', '• Veta na zľavu: „Je to zánovný kus, ale už má pár mikro-škrabancov na ráme, čo pri titáne i17 nejde vyleštiť. Ak pôjdete na 1280 , vezmem ho hneď.“
    • Veta na preverenie: „Môžeme overiť cez IMEI, či nie je braný na paušál, ktorý by sa mohol zablokovať?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 16e', 'Apple', 'iPhone 16e', 'Mobile', '📱 6.1" Super Retina XDR OLED (60Hz panel).', '["⚠️ Action Button: Otestuj jeho odozvu. Musí mať jasný klik, nesmie byť \"zapadnuté\".","⚠️ Haptika: Pusti si budík alebo vibrácie. 16e používa mierne iný vibračný motorček, nesmie v ňom nič hrkotať."]', '🔋 • Čip: A18 (mierne upravená verzia) – stále podporuje Apple Intelligence, čo je kľúčový predajný argument.
    • Audit pravidlo: iPhone 16e ukazuje cykly batérie v Nastavenia -> Informácie.
    • Kontrola: Batéria je o niečo menšia ako v štandardnej 16-ke. Ak je zdravie batérie pod 94 %, priprav sa na častejšie nabíjanie počas dňa.', 'Letecký hliník a prefarbené zadné sklo.', '• Veta na zľavu: „Toto je model 16e, ktorý nemá Camera Control a má slabšiu batériu ako základná 16-ka. Pri zdraví 93 % je tá cena príliš vysoko. Spustíte na 450 ?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 16', 'Apple', 'iPhone 16', 'Mobile', '📱 6.1" Super Retina XDR OLED (60Hz panel).', '["⚠️ Camera Control Swipe: Vyskúšaj v aplikácii Fotoaparát prejsť po tlačidle prstom. Zoom musí byť plynulý, nie skákavý.","⚠️ Magsafe: Skontroluj silu magnetov na zadnej strane."]', '🔋 • Čip: A18 (3nm) – Apple preskočil generáciu (z A16 rovno na A18), aby tento model zvládal AI.
    • Audit pravidlo: iPhone 16 ukazuje cykly batérie (Nastavenia -> Všeobecné -> Informácie).
    • Wau-Fakt: Vďaka novému vnútornému dizajnu sa iPhone 16 menej prehrieva pri hrách než iPhone 15.
    • Kontrola: Pri ročnom zariadení by zdravie malo byť nad 96 %. Ak je nižšie, telefón bol preťažovaný.', 'Letecký hliník a nové, odolnejšie zadné sklo prefarbené v celej štruktúre.', '• Veta na zľavu: „Tento iPhone 16 má už takmer 250 cyklov, čo je na základný model s menšou batériou dosť. Spustíte na 600 ?“
    • Veta na preverenie: „Chcem si len vyskúšať to nové tlačidlo spúšte, či reaguje citlivo na dotyk aj cez toto puzdro.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 16 Plus', 'Apple', 'iPhone 16 Plus', 'Mobile', '📱 6.7" Super Retina XDR OLED (60Hz panel).', '["⚠️ Camera Control Calibration: Ak tlačidlo reaguje \"trhane\", skús ho vyčistiť. Ak to nepomôže, ide o chybu kalibrácie tlaku.","⚠️ Action Button: Nastav si naň svietidlo a skús ho 10x rýchlo za sebou zapnúť/vypnúť."]', '🔋 • Čip: A18 (3nm) – obrovský skok v efektivite oproti A16 v iPhone 15 Plus.
    • Audit pravidlo: iPhone 16 Plus ukazuje počet cyklov priamo v menu (Nastavenia -> Všeobecné -> Informácie).
    • Wau-Fakt: V roku 2026 ide o iPhone s absolútne najdlhšou výdržou na jedno nabitie, vďaka energeticky úspornému čipu a obrovskej batérii.
    • Kontrola: Pri zánovnom kuse hľadaj zdravie 98 – 100 %. Ak má pod 95 %, mobil bol používaný na náročné hry počas nabíjania.', 'Letecký hliník a matné prefarbené zadné sklo (nová, odolnejšia generácia).', '• Veta na zľavu: „Tento Plus model má už 200 cyklov batérie. Keďže je to 60Hz displej, jeho hodnota klesá rýchlejšie ako u Pro modelov. Spustíte na 750 ?“
    • Veta na preverenie: „Chcem si overiť, či Camera Control tlačidlo nemá mŕtve zóny na dotykovej ploche.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 16 Pro', 'Apple', 'iPhone 16 Pro', 'Mobile', '📱 6.3" LTPO Super Retina XDR OLED (nárast z 6.1" u i15 Pro).', '["⚠️ Audio Mix: i16 Pro má 4 nové mikrofóny. Nahraj video a v galérii skús funkciu \"Audio Mix\". Ak sa hlasy nedajú oddeliť od pozadia, mikrofóny nefungujú správne.","⚠️ Action Button: Otestuj, či reaguje na podržanie."]', '🔋 • Čip: A18 Pro (3nm) – optimalizovaný pre Apple Intelligence a ray-tracing v hrách.
    • Audit pravidlo: iPhone 16 Pro ukazuje cykly batérie a dátum výroby priamo v Nastavenia -> Všeobecné -> Informácie.
    • Kontrola: Keďže ide o relatívne nový model, zdravie batérie by malo byť 99–100 %. Ak uvidíš menej ako 97 %, telefón bol pravdepodobne v neustálej záťaži (hry/4K video) pri vysokých teplotách.', 'Titán Grade 5 s novou mikro-pieskovanou úpravou.', '• Veta na zľavu: „Tento model má už 150 cyklov, čo je na ročný telefón dosť. Navyše sú na titáne drobné odreniny, ktoré sa nedajú vyleštiť. Čo tak 900 ?“
    • Veta na preverenie: „Poďme ho reštartovať, aby som videl, či iOS 18+ nehlási chybu konfigurácie nových dielov (najmä Camera Control).“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 16 Pro Max', 'Apple', 'iPhone 16 Pro Max', 'Mobile', '📱 6.9" LTPO Super Retina XDR OLED (najväčší displej v histórii iPhonu).', '["⚠️ Thermal Management: Séria 16 má nový vnútorný rám z recyklovaného hliníka na odvod tepla. Skús spustiť hru alebo benchmark. Ak teplo necítiš na chrbte, ale mobil spomaľuje (throttling), odvod tepla nefunguje.","⚠️ Audio: Má štyri mikrofóny štúdiovej kvality. Nahraj tichý zvuk a skontroluj šum."]', '🔋 • Čip: A18 Pro (3nm) – brutálny výkon pre Apple Intelligence.
    • Audit pravidlo: iPhone 16 Pro Max ukazuje cykly batérie a dátum výroby priamo v Nastavenia -> Informácie.
    • Kontrola: Pri modeli 16 by si mal vidieť zdravie 98-100 %. Ak má pod 95 %, telefón bol vystavovaný extrémnemu teplu (napr. na palubnej doske auta).', 'Grade 5 Titán s novou „pieskovanou“ textúrou (menej sa šmýka ako i15 Pro).', '• Veta na zľavu: „Telefón má už 200 cyklov batérie za prvý rok, čo je dosť intenzívne používanie. Spustíte niečo na fakt, že záruka už čoskoro skončí?“
    • Veta na preverenie: „Môžem skúsiť Camera Control tlačidlo? Počul som, že pri prvých sériách býva zaseknuté.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 15 Pro', 'Apple', 'iPhone 15 Pro', 'Mobile', '📱 LTPO Super Retina XDR OLED, 120Hz ProMotion pre dokonalú plynulosť.', '["⚠️ Display Grain: „Piesok“ pri 5% jase = zľava 100 .","⚠️ Color Gap: Vyžratá PVD vrstva pri tlačidlách.","⚠️ USB-C Rýchlosť: Ak nevidí dáta, port je odpálený."]', '🔋 • Čip: A17 Pro (3nm – prvý svojho druhu, extrémne kúri pri hrách).
    • Wau-Fakt: Ukazuje presný počet cyklov v Nastavenia -> Všeobecné -> Informácie.
    • Audit pravidlo: Nad 300 cyklov je batéria za vrcholom. 0-5 cyklov pri použitom kuse značí podvod a reset cez SW.', 'Titán Grade 5 s vnútorným hliníkom pre odvod tepla.', '• Veta na zľavu: „Tento model má už veľa cyklov. Výmena batérie stojí 100 , spustíte aspoň polovicu?“.
    • Veta na preverenie: „Môžeme ho reštartovať? Chcem overiť kradnuté komponenty cez iOS 18“.', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 15 Pro Max', 'Apple', 'iPhone 15 Pro Max', 'Mobile', '📱 6.7" LTPO Super Retina XDR OLED, 120Hz ProMotion.', '["⚠️ Display Grain: Zľava 100 , ak panel zrní.","⚠️ Color Gap: Vyžratá farba (mapy) na titáne.","⚠️ USB-C Port: Skontroluj vnútro portu. iPhone 15 Pro Max bol prvý s USB-C a veľa ľudí používalo nekvalitné, hrubé káble, ktoré port \"vykývali\". Ak kábel nedrží pevne, oprava portu je u tohto modelu drahá (je na samostatnom flex kábli, ale vyžaduje rozobratie)."]', '🔋 • Kapacita: Najlepšia výdrž v sérii.
    • Audit pravidlo: Ak má nad 300-350 cyklov, batéria už degraduje.
    • Wau-Fakt: Ak má bazárový kus pod 5 cyklov, predajca pravdepodobne nuloval štatistiky softvérom.', 'Titán Grade 5 s hliníkovou základňou.', '• Veta na zľavu: „Tento Max má pnutie skla, riskujem prasknutie. Spustíte niečo z ceny?“.
    • Veta na preverenie: „Môžeme ho reštartovať? Chcem vidieť, či iOS 18 nehlási kradnuté komponenty“.', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 15 Plus', 'Apple', 'iPhone 15 Plus', 'Mobile', '📱 6.7" Super Retina XDR OLED s Dynamic Island.', '["⚠️ Display Grain: „Piesok“ v tme pri 5% jase = vada panelu (zľava 100 ).","⚠️ USB-C Rýchlosť: Ak nevidí dáta v appke Súbory, port je poškodený."]', '🔋 • Čip: A16 Bionic (overený čip z 14 Pro).
    • Wau-Fakt: iPhone 15 Plus je aktuálne kráľom výdrže v Apple ekosystéme. Vďaka menej náročnému displeju často prekonáva aj 15 Pro Max.
    • Audit pravidlo: Nastavenia -> Všeobecné -> Informácie. iPhone 15 Plus ako jeden z prvých ukazuje presný počet cyklov batérie.
    • Kontrola: Nad 300-350 cyklov batéria stráca svoju hlavnú výhodu – extrémnu výdrž. 0-5 cyklov pri použitom kuse = podozrenie na softvérový reset.', 'Letecký hliník a matné prefarbené zadné sklo (farba je priamo v skle).', '• Veta na zľavu: „Tento Plus model má už 350 cyklov, čo pri takej veľkej batérii znamená, že jej čas končí. Spustíte niečo na servis?“
    • Veta na preverenie: „Chcem ho len reštartovať, aby som videl, či iOS 18 nehlási nejaké kradnuté diely.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 14 Pro Max', 'Apple', 'iPhone 14 Pro Max', 'Mobile', '📱 6.7" LTPO Super Retina XDR OLED, 120Hz ProMotion s Dynamic Island.', '[]', '🔋 • Čip: A16 Bionic (4nm) – špičkový výkon, ktorý sa pri záťaži hreje menej než u novšieho modelu 15 Pro.
    • Audit pravidlo: Séria 14 ešte neukazuje počet cyklov priamo v systéme (táto funkcia je exkluzívna pre iPhone 15 a novšie).
    • Kontrola: Musíš sa spoliehať na „Zdravie batérie“ v nastaveniach. Ak je hodnota pod 87 %, batéria už má vrchol svojej životnosti za sebou.', 'Chirurgická nehrdzavejúca oceľ.', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 14 Pro', 'Apple', 'iPhone 14 Pro', 'Mobile', '📱 6,1" LTPO Super Retina XDR OLED, 120Hz ProMotion s Dynamic Island.', '[]', '🔋 • Čip: A16 Bionic (4nm) – špičkový výkon, ktorý sa pri záťaži hreje menej než u novšieho modelu 15 Pro.
    • Audit pravidlo: Séria 14 ešte neukazuje počet cyklov priamo v menu (táto funkcia prišla až s i15).
    • Kontrola: Musíš sa spoliehať na „Zdravie batérie“ v nastaveniach. Ak je hodnota pod 87 %, batéria už má vrchol svojej životnosti za sebou.', 'Chirurgická nehrdzavejúca oceľ.', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 14 Plus', 'Apple', 'iPhone 14 Plus', 'Mobile', '📱 6.7" Super Retina XDR OLED (klasický výrez / Notch).', '["⚠️ Notch Bleed: Pri maximálnom jase skontroluj okolie výrezu (Notch). Ak svetlo presvitá nerovnomerne, displej bol menený za lacnú kópiu.","⚠️ Vibrácie: Skús prepnúť tichý režim. Ak vibračný motorček hrkoce, je uvoľnený."]', '🔋 • Čip: A15 Bionic (5-jadrové GPU) – rovnaký ako v 13 Pro. Stále veľmi výkonný a spoľahlivý.
    • Audit pravidlo: iPhone 14 Plus neukazuje počet cyklov batérie v menu (funkcia až od i15).
    • Kontrola: Musíš sa spoliehať na "Zdravie batérie". Ak je pod 88 %, výdrž batérie (hlavný predajný argument tohto modelu) pôjde rapídne dole.', 'Letecký hliník a lesklé zadné sklo (staršia architektúra než 15-ka).', '• Veta na zľavu: „Tento 14 Plus má už zdravie batérie na 87 %. Keďže to nie je Pro model, batéria je tu jediný dôvod, prečo ho kupujem. Spustíte niečo na jej výmenu?“
    • Veta na preverenie: „Môžeme ho reštartovať? Chcem vidieť, či iOS 18 nehlási nejaké kradnuté diely.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 14', 'Apple', 'iPhone 14', 'Mobile', '📱 6.1" Super Retina XDR OLED (60Hz panel, klasický výrez / Notch).', '["⚠️ Vibrácie: Ak je vibračná odozva (Haptic Touch) tupá alebo hlasná, mobil utrpel silný pád na spodnú hranu.","⚠️ Mikrofón: Nahraj sa na prednú aj zadnú kameru a skús hlasovú poznámku. i14 má 3 mikrofóny, otestuj všetky."]', '🔋 • Čip: A15 Bionic (5-jadrové GPU) – rovnaký čip ako v 13 Pro, čo z 14-ky robí skvelý herný základ.
    • Audit pravidlo: iPhone 14 neukazuje počet cyklov v menu (táto funkcia je až u i15).
    • Kontrola: Sleduj "Zdravie batérie". Ak je pri mobile starom 1-2 roky pod 88 %, bol nabíjaný v aute alebo používaný na hry počas nabíjania.', 'Letecký hliník a lesklé zadné sklo.', '• Veta na zľavu: „Tento model je konštrukčne skoro totožný s i13. Navyše má batériu na 87 %, čo znamená skorú výmenu. Spustíte na 330 ?“
    • Veta na preverenie: „Poďme ho reštartovať, aby som si overil, či systém nehlási neoriginálne diely cez iOS 18.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone SE 2022 (3. gen)', 'Apple', 'iPhone SE 2022 (3. gen)', 'Mobile', '📱 4.7" Retina HD (LCD panel – nie OLED).', '["⚠️ Home Button Click: SE používa Taptic Engine (vibračnú odozvu), nie fyzické tlačidlo. Ak po stlačení mobil zavibruje príliš nahlas alebo plechovo, motorček je uvoľnený."]', '🔋 • Čip: A15 Bionic (rovnaký ako v iPhone 13) – tento mobil bude dostávať aktualizácie ešte dlhé roky.
    • Audit pravidlo: iPhone SE 2022 má malú batériu (2018 mAh). Každé percento zdravia tu zaváži viac než pri modeli Max.
    • Kontrola: Ak je "Zdravie batérie" pod 90 %, pri intenzívnom používaní telefón nevydrží ani do poobedia.', 'Letecký hliník a sklo vpredu aj vzadu.', '• Veta na zľavu: „Je to síce model 2022, ale batéria má už len 86 %. Pri tak malom mobile to znamená, že ho budem musieť nabíjať trikrát denne. Spustíte na výmenu batérie?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 13 Pro Max', 'Apple', 'iPhone 13 Pro Max', 'Mobile', '📱 6.7" LTPO Super Retina XDR OLED, 120Hz ProMotion (prvýkrát v histórii iPhonu).', '["⚠️ Lidar Test: Otvor aplikáciu \"Meradlo\" (Measure). Ak nevidíš body v priestore alebo meria nezmysly, Lidar senzor je poškodený.","⚠️ Reproduktory: Pusti zvuk na 100 %. Horný reproduktor v mriežke nesmie \"bzučať\"."]', '🔋 • Čip: A15 Bionic (5-jadrové GPU) – brutálne efektívny procesor, ktorý sa takmer nehreje.
    • Audit pravidlo: iPhone 13 Pro Max neukazuje počet cyklov v menu (iba cez analytiku alebo PC).
    • Kontrola: "Zdravie batérie" by malo byť ideálne nad 85 %. Tento model má obrovskú batériu, takže aj pri 88 % vydrží viac ako základná 15-ka.', 'Chirurgická nehrdzavejúca oceľ.', '• Veta na zľavu: „Tento model trpí na ''Green Screen'' chybu displeja a tento kus má už batériu na 84 %. Riziko a náklady na servis sú vysoké, spustíte na 450 ?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 13 Pro', 'Apple', 'iPhone 13 Pro', 'Mobile', '📱 6.1" LTPO Super Retina XDR OLED, 120Hz ProMotion.', '["⚠️ Lidar Test: Skús appku \"Measure\" (Meradlo). Ak nevidí hrany stien, senzor je poškodený.","⚠️ Tlačidlá: Oceľové tlačidlá musia mať jasný, kovový zvuk pri kliknutí. Ak sú tiché, mobil bol v tekutine."]', '🔋 • Čip: A15 Bionic (5-jadrové GPU) – brutálne efektívny čip, ktorý starne oveľa pomalšie ako konkurencia.
    • Audit pravidlo: iPhone 13 Pro neukazuje počet cyklov v menu (iba cez analytické dáta alebo PC softvér).
    • Kontrola: Sleduj „Zdravie batérie“. Pri modeli 13 Pro je kritická hranica 86 %. Pod touto hodnotou už pocítiš, že nabíjačku potrebuješ skôr, než skončí deň.', 'Chirurgická nehrdzavejúca oceľ.', '• Veta na zľavu: „Tento model má už zdravie batérie na 84 % a pri 13 Pro to už znamená nutnosť výmeny počas dňa. Navyše riskujem známu chybu bieleho displeja. Spustíte na 380 ?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 13', 'Apple', 'iPhone 13', 'Mobile', '📱 6.1" Super Retina XDR OLED (60Hz panel).', '["⚠️ Vibrácie: Ak vibračná odozva znie „plechovo“ alebo príliš hlasno, vibračný motorček je uvoľnený po páde.","⚠️ Reproduktory: Pusti zvuk na max. Horné slúchadlo nesmie chrčať."]', '🔋 • Čip: A15 Bionic (4-jadrové GPU) – stále brutálne rýchly procesor, takmer identický s tým v iPhone 14.
    • Audit pravidlo: iPhone 13 neukazuje počet cyklov v menu. Musíš sa spoliehať na „Zdravie batérie“.
    • Kontrola: iPhone 13 priniesol veľký skok vo výdrži. Ak je zdravie batérie nad 87 %, mobil ti bez problémov vydrží celý deň. Ak je pod 82 %, priprav si peniaze na servis.', 'Letecký hliník a lesklé zadné sklo.', '• Veta na zľavu: „Tento model je skvelý, ale zdravie batérie má 83 %. Pri iPhone 13 je to už hranica, kedy telefón nevydrží ani do večera. Spustíte na 300 , aby som mohol dať vymeniť batériu?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 13 mini', 'Apple', 'iPhone 13 mini', 'Mobile', '📱 5.4" Super Retina XDR OLED.', '["⚠️ Teplo: Nechaj zapnutý fotoaparát 2 minúty. Ak sa chrbát extrémne rozpáli, batéria je pred smrťou alebo má mobil skrat na doske.","⚠️ Reproduktory: Kvôli malému telu spodný reproduktor pri max. hlasitosti často rezonuje. Skontroluj, či nechrčí."]', '🔋 • Čip: A15 Bionic (4-jadrové GPU) – rovnaký výkon ako v základnej 14-ke.
    • Audit pravidlo: iPhone 13 mini neukazuje cykly v menu.
    • Kritický bod (Battery Life): Výdrž je o 1,5 hodiny lepšia ako u 12 mini, ale stále je to malý telefón.
    • Kontrola: Ak je „Zdravie batérie“ pod 88 %, telefón ti nevydrží ani do konca pracovnej doby. Pri 13 mini je batéria kritickým parametrom nákupu.', 'Letecký hliník a lesklé zadné sklo.', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 12 Pro Max', 'Apple', 'iPhone 12 Pro Max', 'Mobile', '📱 6.7" Super Retina XDR OLED (60Hz panel – pozor, nemá 120Hz ProMotion).', '["⚠️ 5G Test: Zapni dáta. Séria 12 mala prvú generáciu 5G modemov, ktoré sa radi prehrievali. Ak po minúte na 5G telefón horí, modem má problém.","⚠️ MagSafe: Prilož MagSafe nabíjačku. Musí držať pevne v strede. Ak lieta, magnety sú uvoľnené alebo je zadné sklo neoriginálne."]', '🔋 • Čip: A14 Bionic (5nm) – prvý 5G čip v iPhone. Stále dostatočne výkonný, ale energeticky menej efektívny než novšie A15.
    • Audit pravidlo: iPhone 12 Pro Max neukazuje cykly v menu.
    • Kontrola: Zdravie batérie pod 85 % je pri tomto modeli už kritické. Batéria v rade 12 bola o niečo menšia než v rade 13, takže degradácia je tu citeľnejšia.', 'Chirurgická nehrdzavejúca oceľ a Ceramic Shield vpredu.', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 12 Pro', 'Apple', 'iPhone 12 Pro', 'Mobile', '📱 6,1" Super Retina XDR OLED (60Hz panel – pozor, nemá ProMotion).', '["⚠️ Earpiece Recall: Apple mal výmenný program na i12 Pro kvôli zlyhávajúcim slúchadlám. Pusti hovor – ak slúchadlo nepočuť alebo chrčí, ide o túto vadu.","⚠️ Lidar: Skús appku Meradlo (Measure). Musí okamžite detegovať roviny."]', '🔋 • Čip: A14 Bionic (5nm) – prvý 5G čip od Apple.
    • Audit pravidlo: iPhone 12 Pro neukazuje cykly v menu.
    • Kontrola: Batéria je slabinou rady 12. Má kapacitu len 2815 mAh. Ak je "Zdravie batérie" pod 85 %, telefón budeš musieť nabíjať minimálne 2x denne.', 'Chirurgická nehrdzavejúca oceľ.', '• Veta na zľavu: „Tento model má už zdravie batérie na 84 % a vieme, že 12 Pro mala menšiu batériu než 11 Pro alebo 13 Pro. Spustíte niečo na jej výmenu?“
    • Veta na preverenie: „Môžeme ho reštartovať? Chcem overiť, či iOS 18 nehlási neoriginálne komponenty.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 12', 'Apple', 'iPhone 12', 'Mobile', '📱 6.1" Super Retina XDR OLED (veľký skok oproti LCD v iPhone 11).', '["⚠️ Sound Recall: Apple uznal chybu so slúchadlom (No Sound Issue) pri i12 vyrobených medzi 10/2020 a 04/2021. Pusti hovor – ak je ticho, telefón je vadný.","⚠️ Vibrácie: Taptic engine u i12 občas po páde začne „bzučať“. Skús prepnúť tichý režim."]', '🔋 • Čip: A14 Bionic – prvý 5nm čip s podporou 5G. Stále veľmi svižný.
    • Audit pravidlo: iPhone 12 neukazuje počet cyklov v menu.
    • Kritický bod: Batéria i12 má kapacitu len 2815 mAh (menej ako i11). Ak je "Zdravie batérie" pod 86 %, výdrž bude tvojím hlavným nepriateľom.
    • Kontrola: Ak zdravie batérie svieti na 100 % pri 3-ročnom mobile, bola menená. Over, či systém nehlási "Neznámy diel".', 'Letecký hliník a lesklé zadné sklo.', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('iPhone 12 mini', 'Apple', 'iPhone 12 mini', 'Mobile', '📱 5.4" Super Retina XDR OLED.', '["⚠️ Magsafe Heat: Prilož Magsafe nabíjačku. Ak sa mobil okamžite extrémne rozpáli, batéria má vysoký vnútorný odpor a čoskoro \"napuchne\".","⚠️ Slúchadlo: Pusti si hlasitý odposluch a potom prepni na horné slúchadlo. Nesmie v ňom praskať (častá vada rady 12)."]', '🔋 • Čip: A14 Bionic (5G podpora).
    • Kritický bod (The Weakness): Batéria je najväčšou slabinou tohto modelu (len 2227 mAh).
    • Audit pravidlo: iPhone 12 mini neukazuje cykly v menu.
    • Kontrola: Ak je "Zdravie batérie" pod 87 %, telefón je reálne nepoužiteľný bez powerbanky po 14:00 hodine. Ak vidíš zdravie 100 % pri bazárovom kuse, batéria bola menená (over, či za originál).', 'Letecký hliník a Ceramic Shield.', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('PlayStation 5 (Disc/Digital)', 'Sony', 'PlayStation 5 (Disc/Digital)', 'Console', '📱 ', '["⚠️ Optical Drive (Disc Jam): Vyskúšaj tlačidlo Eject 3-krát po sebe. Ak mechanika váha alebo vydáva kovový zvuk, ozubené kolieska sú opotrebované.","⚠️ Coil Whine (Bzučanie): Prilož ucho k zadnej časti pri spustenej hre. Silné elektrické bzučanie indikuje lacné cievky v zdroji – je to hlučné a otravné.","⚠️ Port Wear (USB-C): Predný USB-C port u PS5 často stráca kontakt. Skontroluj, či sa ovládač nabíja stabilne.","⚠️ HDMI Port (The Flashlight Test): Zasvieť si priamo do HDMI portu. Ak vidíš, že piny sú ohnuté alebo je port mierne zatlačený dnu, konzola bola neodborne prenášaná s káblom vnútri. Oprava HDMI portu stojí u PS5 okolo 100 , lebo je pripájaný priamo na dosku.","⚠️ Controller Drift: Ak predajca dáva k PS5 ovládač DualSense, otvor v menu konzoly nastavenia a skús pohybovať páčkami. Ak sa kurzor hýbe sám, ovládač má \"Stick Drift\" – zľava 50  na nový."]', '🔋 ', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Xbox Series X', 'Microsoft', 'Xbox Series X', 'Console', '📱 ', '["⚠️ SSD Wear (Loading Time): Spusti hru \"Forza\" alebo \"Halo\". Ak načítavanie trvá viac ako 15 sekúnd, SSD má poškodené bunky a stráca rýchlosť.","⚠️ Quick Resume Glitch: Ak prepneš medzi 3 hrami a konzola \"spadne\" do menu, pamäťový modul Quick Resume je prehriaty a nestabilný.","⚠️ Top Grill Dust: Ak je pod hornou mriežkou viditeľný biely prach, konzola bola v prostredí s fajčiarom alebo domácimi zvieratami – hrozí skrat."]', '🔋 ', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Nintendo Switch (V2 / OLED / Lite)', 'Nintendo', 'Nintendo Switch (V2 / OLED / Lite)', 'Console', '📱 6.2" LCD (V2), 7" OLED (OLED), 5.5" LCD (Lite).', '["⚠️ Green Tint: Niektoré OLED panely majú pri nízkom jase zelený nádych. Skontroluj to v tme.","⚠️ Kickstand: Zadný stojan u OLED verzie je cez celý chrbát. Musí držať v každom uhle. Ak \"padá\", kåb je vybehaný."]', '🔋 • Wau-Pikoška (The Fan): Nintendo Switch má aktívny ventilátor. Ak ho po 5 minútach hrania nepočuješ alebo konzola začne pípať, chladenie je mŕtve.
    • Audit pravidlo: Model V2 (červená krabica) má oveľa lepšiu výdrž ako stará V1 (sivá krabica). Ak predajca predáva starú V1 za cenu V2, klame. Skontroluj kód modelu (V2 začína na XKW).', '', '• Red Flag: Predajca povie: „Dám vám k tomu hry na mojom účte.“ – KLAMSTVO. Predajca si účet kedykoľvek vezme späť cez e-mail. Účet má nulovú hodnotu.
    • Veta na zľavu: „Páčky už začínajú driftovať a displej sa v rohu odlepuje. Servis ma vyjde na 50 , spustíte to z ceny?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('ASUS ROG (Strix / Zephyrus)', 'ASUS', 'ASUS ROG (Strix / Zephyrus)', 'Laptop', '📱 IPS/Mini-LED panely s vysokou frekvenciou (144Hz – 300Hz).', '["⚠️ Fan Whine: Ak ventilátory vydávajú vysoký piskľavý zvuk, ložiská sú v háji. Výmena ventilátora v autorizáku stojí cca 80 .","⚠️ Chassis Cracks: Skontroluj spodné plasty. Ak sú tam praskliny pri výduchoch, notebook bol prehrievaný tak, že plast skreholl a praskol."]', '🔋 • Wau-Pikoška (The Barrel Plug): Napájacie konektory ASUS ROG sú náchylné na prehrievanie. Ak je plast okolo konektora na notebooku deformovaný alebo smrdí po spálenine, základná doska je na ceste do hrobu.
    • Audit pravidlo: Batéria v hernom notebooku je po 2 rokoch často na 50 % kapacity. Skontroluj to cez príkaz powercfg /batteryreport vo Windows.', '', '• Red Flag: „Notebook bol používaný len na prácu v Office.“ – LO. Nikto si nekupuje hučiaci ASUS ROG s RTX grafikou na Excel. Notebook bol určite "týraný" hrami.
    • Veta na zľavu: „Teploty v záťaži atakujú $100^{\circ}C$ a ventilátory pískajú. Vyčistenie a výmena tekutého kovu ma vyjde na 120 . Pustíte to z ceny?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Lenovo Legion (5 / 5 Pro / 7)', 'Lenovo', 'Lenovo Legion (5 / 5 Pro / 7)', 'Laptop', '📱 15.6" alebo 16" (Pro verzia) s pomerom strán 16:10. pičkový jas až 500 nitov.', '["⚠️ Touchpad Rattle: U Legionov 5 sa touchpad často uvoľní a pri dotyku \"kliká\" naprázdno. Otravná mechanická vada.","⚠️ Keycaps Shine: Skontroluj klávesy Space a Shift. Ak sú vyleštené do zrkadla, notebook má nabehané tisíce hodín v e-športoch.","⚠️ Lenovo Legion 5 (Standard): Väčšinou sa dodáva s 230W adaptérom. Ten je o niečo tenší a ľahší. Ak k nemu dostaneš 300W, je to bonus (bude sa menej hriať), ale ak dostaneš menej ako 230W, notebook sa bude pri hraní vybíjať aj na kábli."]', '🔋 • Wau-Pikoška (Hybrid Mode): Legion má MUX Switch. Ak je vypnutý, notebook ide len na výkonnú grafiku a batéria vydrží ledva 45 minút.
    • Audit pravidlo: V aplikácii Lenovo Vantage skontroluj počet cyklov. Ak je nad 300, batéria v hernom stroji už nebude držať kapacitu pri náročnej práci.', '', '• Red Flag: Predajca, ktorý má na notebooku nalepených milión nálepiek – často tým maskuje škrabance alebo praskliny v plastovom šasi.
    • Veta na zľavu: „Pánty pri otváraní pukajú, čo je u Legionov známy začiatok konca. Oprava stojí skoro dve stovky. Spustíte z ceny, alebo to riskovať nebudem?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('HP Omen (15, 16, 17)', 'HP', 'HP Omen (15, 16, 17)', 'Laptop', '📱 Kvalitné IPS panely (často 144Hz/165Hz). Omen 17 má masívne chladenie, ktoré patrí k špičke.', '[]', '🔋 • Wau-Pikoška (Omen Gaming Hub): Umožňuje podvoltovanie (undervolting) priamo od výrobcu.
    • Audit pravidlo: Ak predajca tvrdí, že notebook "vydrží 6 hodín", pri Omenoch s i7 procesorom mu never. Reálna hodnota je okolo 2-3 hodín.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('HP Victus (15, 16)', 'HP', 'HP Victus (15, 16)', 'Laptop', '📱 Často lacnejšie 144Hz panely s nižším farebným pokrytím (250 nitov).', '["⚠️ Speaker Crackle: Reproduktory Bang & Olufsen u Omenov radi \"praskajú\" pri basoch. Daj hlasitosť na 100% a skús trailer na film.","⚠️ Key Ghosting: Otestuj, či funguje stlačenie viacerých kláves naraz (N-Key Rollover)."]', '🔋 ', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('MSI (Katana / Cyborg / GF)', 'MSI', 'MSI (Katana / Cyborg / GF)', 'Laptop', '📱 144Hz IPS panely, často s nižším jasom (250 nitov) a horším podaním farieb.', '[]', '🔋 ', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('MSI (Stealth / Raider)', 'MSI', 'MSI (Stealth / Raider)', 'Laptop', '📱 ', '["⚠️ Plastic Creaking: Ak notebook pri zdvihnutí jednou rukou „vŕzga“, šasi je skrútené a vnútorné spoje sú pod tlakom.","⚠️ Screen Flex: Displej je veľmi tenký a ohybný. Skontroluj, či v obraze nie sú biele fľaky od tlaku prstov pri otváraní."]', '🔋 ', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Acer Nitro 5 / Nitro V', 'Acer', 'Acer Nitro 5 / Nitro V', 'Laptop', '📱 144Hz IPS panely. Staršie modely majú horšie farby (62% sRGB), novšie Nitro V sú na tom lepšie.', '[]', '🔋 • Wau-Pikoška (The Double Click): Napájací kábel u Aceru musí do portu "zacvaknúť" dvakrát. Ak nedrží pevne, port je vybitý a bude sa prehrievať.
    • Audit pravidlo: Batéria u Nitro série je slabá už od výroby. Po 2 rokoch rátaj s výdržou max. 60-90 minút v Office režime.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Acer Predator (Helios / Triton)', 'Acer', 'Acer Predator (Helios / Triton)', 'Laptop', '📱 ', '["⚠️ Speaker Distortion: Reproduktory u Nitra sú podpriemerné. Ak pri 80% hlasitosti vibruje celé šasi, membrány sú uvoľnené.","⚠️ Touchpad Click: Ak je kliknutie touchpadu \"tupé\" alebo sa nevracia, batéria pod ním sa pravdepodobne nafukuje."]', '🔋 ', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Razer Blade (14 / 15 / 17)', 'Razer', 'Razer Blade (14 / 15 / 17)', 'Laptop', '📱 pičkové panely (QHD 165Hz/240Hz alebo 4K OLED). Farebná presnosť je u Razeru bezkonkurenčná.', '["⚠️ Anodized Coating Wear: Skontroluj miesta pri USB portoch. Čierny elox sa u Razeru rýchlo ošúcha na strieborný hliník – indikácia drsného používania.","⚠️ Webcam/Windows Hello: Razer kamery často odchádzajú kvôli teplu z displeja. Skontroluj, či Windows Hello (prihlásenie tvárou) funguje okamžite."]', '🔋 • Wau-Pikoška (Bloating): 80 % bazárových Razerov starších ako 2 roky má alebo malo nafúknutú batériu. Je to konštrukčná vada spôsobená teplom.
    • Audit pravidlo: Skontroluj, či funguje klikanie touchpadu. Ak ide kliknúť ťažko alebo vôbec, batéria pod ním je už nafúknutá. OKAMITE VYMENI, hrozí požiar alebo zničenie šasi.', '', '• Red Flag: „Batéria je odpojená, používam ho len na kábli.“ – To znamená, že batéria bola taká nafúknutá, že ju musel vyhodiť, aby notebook nevybuchol.
    • Veta na zľavu: „U tohto modelu je nafukovanie batérie len otázkou času a táto už tlačí na touchpad. Výmena batérie a servis ma vyjdú na 150 . Spustíte to z ceny?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('AirPods Pro (1. & 2. Gen)', 'Apple', 'AirPods Pro (1. & 2. Gen)', 'Mobile', '📱 ', '["⚠️ The Mesh Check: Zlož silikónový štupeľ. Pod ním musí byť čierna mriežka zapustená v tele. Fejky tam majú často len prázdnu dieru.","⚠️ Pressure Vent: Čierna mriežka na vrchu slúchadla musí byť skutočná mriežka. Ak je to len čierny nástrek/nálepka, je to fejk."]', '🔋 • Audit pravidlo: Batéria v AirPods sa nedá vymeniť. Po 3 rokoch vydržia často len 30–60 minút.
    • Checklist: Ak predajca povie „dlho som ich nepoužíval“, je to varovný signál – batéria chemicky degraduje najrýchlejšie práve pri hlbokom vybití.
    • Pro 2 Volume Swipe: Prejdi prstom po "nožičke" nahor/nadol. Ak hlasitosť nereaguje, dotyková vrstva (alebo celá elektronika fejku) je vadná.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('ASUS ROG (Strix / Zephyrus)', 'ASUS', 'ASUS ROG (Strix / Zephyrus)', 'Laptop', '📱 IPS/Mini-LED panely s vysokou frekvenciou (144Hz – 300Hz).', '["⚠️ Fan Whine: Ak ventilátory vydávajú vysoký piskľavý zvuk, ložiská sú v háji. Výmena ventilátora v autorizáku stojí cca 80 .","⚠️ Chassis Cracks: Skontroluj spodné plasty. Ak sú tam praskliny pri výduchoch, notebook bol prehrievaný tak, že plast skreholl a praskol."]', '🔋 • Wau-Pikoška (The Barrel Plug): Napájacie konektory ASUS ROG sú náchylné na prehrievanie. Ak je plast okolo konektora na notebooku deformovaný alebo smrdí po spálenine, základná doska je na ceste do hrobu.
    • Audit pravidlo: Batéria v hernom notebooku je po 2 rokoch často na 50 % kapacity. Skontroluj to cez príkaz powercfg /batteryreport vo Windows.', '', '• Red Flag: „Notebook bol používaný len na prácu v Office.“ – LO. Nikto si nekupuje hučiaci ASUS ROG s RTX grafikou na Excel. Notebook bol určite "týraný" hrami.
    • Veta na zľavu: „Teploty v záťaži atakujú $100^{\circ}C$ a ventilátory pískajú. Vyčistenie a výmena tekutého kovu ma vyjde na 120 . Pustíte to z ceny?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Acer Nitro 5 / Nitro V', 'Acer', 'Acer Nitro 5 / Nitro V', 'Laptop', '📱 144Hz IPS panely. Staršie modely majú horšie farby (62% sRGB), novšie Nitro V sú na tom lepšie.', '[]', '🔋 • Wau-Pikoška (The Double Click): Napájací kábel u Aceru musí do portu "zacvaknúť" dvakrát. Ak nedrží pevne, port je vybitý a bude sa prehrievať.
    • Audit pravidlo: Batéria u Nitro série je slabá už od výroby. Po 2 rokoch rátaj s výdržou max. 60-90 minút v Office režime.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Acer Predator (Helios / Triton)', 'Acer', 'Acer Predator (Helios / Triton)', 'Laptop', '📱 ', '["⚠️ Speaker Distortion: Reproduktory u Nitra sú podpriemerné. Ak pri 80% hlasitosti vibruje celé šasi, membrány sú uvoľnené.","⚠️ Touchpad Click: Ak je kliknutie touchpadu \"tupé\" alebo sa nevracia, batéria pod ním sa pravdepodobne nafukuje."]', '🔋 ', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Razer Blade (14 / 15 / 17)', 'Razer', 'Razer Blade (14 / 15 / 17)', 'Laptop', '📱 pičkové panely (QHD 165Hz/240Hz alebo 4K OLED). Farebná presnosť je u Razeru bezkonkurenčná.', '["⚠️ Anodized Coating Wear: Skontroluj miesta pri USB portoch. Čierny elox sa u Razeru rýchlo ošúcha na strieborný hliník – indikácia drsného používania.","⚠️ Webcam/Windows Hello: Razer kamery často odchádzajú kvôli teplu z displeja. Skontroluj, či Windows Hello (prihlásenie tvárou) funguje okamžite."]', '🔋 • Wau-Pikoška (Bloating): 80 % bazárových Razerov starších ako 2 roky má alebo malo nafúknutú batériu. Je to konštrukčná vada spôsobená teplom.
    • Audit pravidlo: Skontroluj, či funguje klikanie touchpadu. Ak ide kliknúť ťažko alebo vôbec, batéria pod ním je už nafúknutá. OKAMITE VYMENI, hrozí požiar alebo zničenie šasi.', '', '• Red Flag: „Batéria je odpojená, používam ho len na kábli.“ – To znamená, že batéria bola taká nafúknutá, že ju musel vyhodiť, aby notebook nevybuchol.
    • Veta na zľavu: „U tohto modelu je nafukovanie batérie len otázkou času a táto už tlačí na touchpad. Výmena batérie a servis ma vyjdú na 150 . Spustíte to z ceny?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Ultra (1 & 2)', 'Apple', 'Apple Watch Ultra (1 & 2)', 'Mobile', '📱 Plochý zafírový kryštál, jas 2000 nitov (U1) alebo 3000 nitov (U2).', '["⚠️ Speaker Grill: Ultra má dva otvory pre reproduktor. Pusti sirénu na 1 sekundu (pozor, bolí to). Zvuk musí byť čistý. Ak \"chrčí\", membrány sú pretrhnuté.","⚠️ Backlight Leak: V úplnej tme pri čiernom pozadí nesmie titánový rám \"presvitať\". Ak áno, displej nie je OLED, ale lacné LCD – jasný dôkaz fejku."]', '🔋 • Čip: S8 (Ultra 1) alebo S9 (Ultra 2). Ultra 2 prináša "Double Tap" gesto a rýchlejšiu Siri priamo v hodinkách.
    • Audit pravidlo: Batéria u Ultra je masívna. Ak má zdravie (Battery Health) pod 92 % u modelu Ultra 2, hodinky boli extrémne tepelne namáhané (časté rýchlonabíjanie v horúčavách).
    • Kontrola: Pri Ultra 1 je zdravie okolo 85–88 % po dvoch rokoch bežné, pod 80 % je to už dôvod na výraznú zľavu.', '', '• Veta na zľavu: „Vidím, že titánový rám je na hranách dosť obitý, čo u tohto modelu znižuje vodotesnú integritu. Navyše remienok nie je originál Apple. Spustíte na 480 ?“
    • Veta na preverenie: „Môžem vyskúšať, či senzor håbky a barometra reaguje správne v aplikácii?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Series 11', 'Apple', 'Apple Watch Series 11', 'Mobile', '📱 Nový OLED panel s technológiou LTPO3, jas až 2500 nitov (vyrovnáva sa pôvodnej Ultra).', '["⚠️ Magnet Interference: Prilož hodinky k inému magnetu (napr. iPad cover). Ak sa samovoľne odopne remienok, magnetický zámok v hodinkách je oslabený.","⚠️ Microphone Hole: S11 má dva mikrofóny na ľavej strane. Skontroluj, či nie sú zanesené kožným mazom – drasticky to znižuje kvalitu diktovania správ."]', '🔋 • Čip: S11 SiP s dedikovaným 8-jadrovým Neural Enginom pre Apple Intelligence.
    • Wau-Pikoška (Vitals 2.0): Hodinky dokážu predpovedať prichádzajúcu chorobu (napr. chrípku) až 24 hodín vopred vďaka analýze nočných biometrických dát.
    • Audit pravidlo: Zdravie batérie (Battery Health) pod 98 % po pár mesiacoch je pri tomto modeli varovné – S11 má nové rýchlejšie nabíjanie, ktoré pri použití neoriginálnych adaptérov batériu prehrieva.
    • Kontrola: Nabitie z 0 na 80 % musí trvať cca 30 minút.', '', '• Veta na zľavu: „Keďže Apple zmenil systém remienkov, všetky moje doterajšie sú mi bez drahého adaptéra nanič. Navyše Series 10 má takmer rovnakú výdrž. Spustíte 40  na ten adaptér?“
    • Veta na preverenie: „Funguje na tomto kuse už to nové predpovedanie chorôb (Vitals)? Chcem vidieť graf za posledný týždeň.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Ultra 3', 'Apple', 'Apple Watch Ultra 3', 'Mobile', '📱 1.93" microLED (alebo vylepšený LTPO3 OLED s vysokou hustotou), jas až 3500 nitov.', '["⚠️ Speaker Grill (Dust Guard): Ultra 3 má nové jemnejšie mriežky reproduktorov. Ak uvidíš hrubé diery bez sieťky, je to starší model alebo fejk.","⚠️ Titanium Finish: Skontroluj spodnú stranu (okolo senzorov). Písmo musí byť laserom vygravírované do titánu, nie len natlačené."]', '🔋 • Čip: S11 SiP (rovnaký ako v S11, ale s lepším chladením).
    • Wau-Pikoška (Low Power Mode+): V novom ultra-úspornom režime vydržia hodinky až 80 hodín so zapnutým GPS.
    • Audit pravidlo: Pri novom kuse vyžaduj 100 % zdravie batérie. Ultra 3 má masívny akumulátor; ak po mesiaci klesne na 99 %, majiteľ ich pravdepodobne nabíjal v extrémne horúcom prostredí (napr. na palubnej doske auta).', '', '• Veta na zľavu: „Táto nová čierna farba je náchylná na odreniny v rohoch pri displeji a tento kus už má pár bodiek. Keďže ide o prémiový model, chcel by som zľavu na prelakovanie alebo opravu.“
    • Veta na preverenie: „Môžete mi ukážať históriu potápania v aplikácii Oceanic+? Chcem vidieť, v akej håbke boli hodinky reálne testované.“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch SE 3', 'Apple', 'Apple Watch SE 3', 'Mobile', '📱 Retina LTPO OLED, jas 1000 nitov.', '["⚠️ Water Damage Check: SE 3 majú indikátor vlhkosti skrytý v porte pod remienkom. Ak tam uvidíš červenú bodku (použi lupu), hodinky boli \"utopené\".","⚠️ Side Button: Tlačidlo pod korunkou musí mať jasný mechanický klik. Ak je \"gumové\", je pod ním špina alebo je poškodené pádom na bok."]', '🔋 • Čip: S10 SiP (rovnaký ako v Series 10). Hodinky sú extrémne rýchle a podporujú väčšinu AI funkcií.
    • Wau-Pikoška (The Endurance): Vďaka absencii Always-On displeja a efektívnemu čipu majú SE 3 najlepšiu reálnu výdrž v "malej" kategórii (často viac ako 24 hodín).
    • Audit pravidlo: Zdravie batérie by pri modeli z roku 2025/2026 malo byť nad 96 %. Ak je nižšie, hodinky boli "trápene" v nabíjačke celú noc každý deň.', '', '• Red Flag: Predajca, ktorý tvrdí, že hodinky sú z hliníka. SE 3 sú kompozitné (plastové). Ak to nevie, buď ich sám neoveroval, alebo zavádza o modeli.
    • Veta na zľavu: „Tento model je z plastu a nemá Always-On displej ani EKG. Navyše má škrabance na skle, ktoré sa nedajú vyleštiť. Spustíte 40  na nový remienok a adaptér?“', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Series 10', 'Apple', 'Apple Watch Series 10', 'Mobile', '📱 Prvý Wide-angle OLED displej od Apple. Je optimalizovaný na čitateľnosť z extrémnych uhlov.', '["⚠️ The Haptic Crown: Pri točení korunkou v menu musíš cítiť jemné, presné \"klikanie\". Ak je haptika tupá alebo vibruje celé telo hodiniek, vibračný motorček (Taptic Engine) je uvoľnený.","⚠️ Glass Curvature: Sklo Series 10 zachádza hlbšie do strán. Prejdi prstom po okraji – prechod musí byť dokonale hladký. Ak cítiš hranu, displej bol prelepovaný."]', '🔋 • Čip: S10 SiP.
    • Wau-Pikoška (Fastest Charge): S10 má najrýchlejšie nabíjanie v histórii Apple Watch – na 80 % sa nabijú za 15 minút.
    • Audit pravidlo: Kvôli extrémnemu rýchlonabíjaniu batéria viac trpí teplom. Pri kuse z druhej ruky (po 1,5 roku používania) očakávaj zdravie okolo 88 – 92 %.
    • Kontrola: Ak predajca tvrdí, že majú 100 % po roku používania, zbystri – buď boli málo nosené, alebo bol softvérovo zresetovaný ukazovateľ.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Ultra (1. generácia)', 'Apple', 'Apple Watch Ultra (1. generácia)', 'Mobile', '📱 ', '[]', '🔋 Audit pravidlo: Po 3+ rokoch (v roku 2026) bude zdravie batérie pravdepodobne medzi 82 % – 86 %.
        ? Kritický bod: Ak má batéria pod 80 %, hodinky strácajú schopnosť udržať výkon v mraze (vypnú sa ti na lyžovačke).
    • ? 4. PREČO KÚPI: Najlacnejšia cesta k Ultra dizajnu a skvelej odolnosti.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Ultra 2', 'Apple', 'Apple Watch Ultra 2', 'Mobile', '📱 ', '["⚠️ The Backplate Test: Otoč hodinky. Musia tam byť 4 skutočné skrutky a dva poistné gombíky na remienky. Fejky majú skrutky len nakreslené alebo vylisované.","⚠️ The Weight: Originál Ultra váži presne 61.3 - 61.8 gramov (bez remienka). Ak máš vreckovú váhu a hodinky majú 45-50g, je to plastový fejk."]', '🔋 Wau-Fakt (Double Tap): U2 podporuje gesto poklepania prstami (palec a ukazovák).
        ? Checklist: Vyskúšaj Double Tap na prijatie hovoru alebo zastavenie budíka. Ak nereaguje, môže byť vadný akcelerometer alebo ide o fejkovú základnú dosku.
    • ? 4. SENZORY: Lokálne spracovanie Siri (funguje aj bez internetu).
        ? Checklist: Daj Siri príkaz: "Začni cvičenie beh." Musí reagovať okamžite bez "točiaceho sa" kolieska.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Series 9', 'Apple', 'Apple Watch Series 9', 'Mobile', '📱 Always-On Retina OLED, jas až 2000 nitov.', '["⚠️ Microphone Test: Spusti Diktafón. S9 má vylepšené mikrofóny. Ak je zvuk zahmlený, do mikrofónu (dierka na boku) sa dostal krém alebo prach.","⚠️ Back Ceramic: Spodná strana je keramická. Hľadaj praskliny v tvare pavučiny. Ak sú tam, senzor nebude presne merať tep a hrozí podráždenie pokožky."]', '🔋 • Čip: S9 SiP (prvý zásadný skok vo výkone po rokoch).
    • Wau-Pikoška (Double Tap): Toto je kľúčová funkcia S9. Dvojité poklepanie prstami (palec o ukazovák) bez dotyku displeja.
    • Checklist: Aktivuj hodinky a skús Double Tap na zastavenie budíka alebo prijatie správy. Ak gesto nefunguje ani po zapnutí v nastaveniach, hodinky majú chybný akcelerometer alebo ide o staršiu Series 8 v tele S9.
    • Audit pravidlo: Po 2 rokoch (v 2026) by zdravie batérie malo byť medzi 87 % – 93 %.', '', '', NULL);
INSERT INTO products (name, brand, model_name, category, display_tech, common_faults, battery_risks, frame_material, negotiation_tips, base_price_recommended) VALUES ('Apple Watch Series 8', 'Apple', 'Apple Watch Series 8', 'Mobile', '📱 Always-On Retina LTPO OLED, jas 1000 nitov.', '["⚠️ Microphone/Speaker Hole: S8 má jeden dlhý výrez na reproduktor. Ak je v ňom vidieť zaschnuté blato alebo soľ, mikrofón (malá dierka vedľa) bude hluchý.","⚠️ Color Fading: Pri hliníkovej verzii \"Midnight\" (tmavomodrá/čierna) sa často ošúchava farba okolo spodného okraja."]', '🔋 • Čip: S8 SiP (prakticky rovnaký výkon ako S6 a S7).
    • Audit pravidlo: V roku 2026 bude mať väčšina kusov S8 zdravie batérie medzi 80 % – 85 %.
    • Kritický bod: Ak je zdravie 80 % alebo menej, hodinky začnú sekať pri náročnejších aplikáciách a nevydržia ani od rána do večera. Trvaj na výraznej zľave na výmenu batérie.
    • Low Power Mode: Series 8 bola prvá, ktorá prišla s novým úsporným režimom (výdrž až 36 hodín).', '', '', NULL);
